services:
  archivo-oasis:
    image: ghcr.io/jbaezami/archivo-oasis:latest
    container_name: archivo-oasis
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - default
      - red-cloudflare

networks:
  red-cloudflare:
    external: true
