services:
  archivo-oasis:
    image: ghcr.io/jbaezami/archivo-oasis:latest
    container_name: archivo-oasis
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - default
      - red-cloudflare
    depends_on:
      - archivo-oasis-api

  archivo-oasis-api:
    image: ghcr.io/jbaezami/archivo-oasis-api:latest
    container_name: archivo-oasis-api
    restart: unless-stopped
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - ADMIN_JELLYFIN_USERNAME=${ADMIN_JELLYFIN_USERNAME}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - archivo-oasis-data:/data
    networks:
      - default

networks:
  red-cloudflare:
    external: true

volumes:
  archivo-oasis-data:
